In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
%matplotlib
import seaborn as sns
sns.set()

Using matplotlib backend: module://matplotlib_inline.backend_inline

In [6]:
df=pd.read_excel(r'C:\Users\hp\Desktop\Decodelabs Internship\Dataset for Data Analytics.xlsx')

In [7]:
df.describe()

                      Date     Quantity    UnitPrice  ItemsInCart   TotalPrice
count                 1200  1200.000000  1200.000000  1200.000000  1200.000000
mean   2024-03-22 16:58:48     2.945833   356.412750     5.485000  1053.968300
min    2023-01-01 00:00:00     1.000000    11.390000     1.000000    11.390000
25%    2023-08-03 18:00:00     2.000000   186.062500     4.000000   410.520000
50%    2024-03-23 00:00:00     3.000000   364.210000     5.000000   823.615000
75%    2024-11-08 12:00:00     4.000000   521.570000     7.000000  1578.475000
max    2025-06-30 00:00:00     5.000000   699.930000    10.000000  3456.400000
std                    NaN     1.407557   197.177146     2.281983   819.856558

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   OrderID          1200 non-null   object
 1   Date             1200 non-null   datetime64[ns]
 2   CustomerID       1200 non-null   object
 3   Product          1200 non-null   object
 4   Quantity         1200 non-null   int64
 5   UnitPrice        1200 non-null   float64
 6   ShippingAddress  1200 non-null   object
 7   PaymentMethod    1200 non-null   object
 8   OrderStatus      1200 non-null   object
 9   TrackingNumber   1200 non-null   object
 10  ItemsInCart      1200 non-null   int64
 11  CouponCode       891 non-null    object
 12  ReferralSource   1200 non-null   object
 13  TotalPrice       1200 non-null   float64
dtypes: datetime64[ns](1), float64(2), int64(2), object(9)
memory usage: 131.4+ KB

In [10]:
df.isna().sum()

OrderID              0
Date                 0
CustomerID           0
Product              0
Quantity             0
UnitPrice            0
ShippingAddress      0
PaymentMethod        0
OrderStatus          0
TrackingNumber       0
ItemsInCart          0
CouponCode         309
ReferralSource       0
TotalPrice           0
dtype: int64

In [19]:
df.head(100)

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,ORD200095,2023-03-24,C76761,Printer,4,117.51,839 Main St,Debit Card,Returned,TRK60179774,7,NaN,Referral,470.04
96,ORD200096,2024-06-01,C93007,Phone,2,232.83,103 Main St,Gift Card,Delivered,TRK85696091,7,NaN,Instagram,465.66
97,ORD200097,2025-01-21,C15624,Tablet,5,619.52,922 Main St,Debit Card,Pending,TRK40621141,9,NaN,Email,3097.60
98,ORD200098,2023-01-14,C70921,Printer,2,228.54,533 Main St,Debit Card,Pending,TRK54983109,3,NaN,Email,457.08
99,ORD200099,2025-04-12,C30477,Printer,1,201.58,717 Main St,Debit Card,Cancelled,TRK51829648,2,WINTER15,Email,201.58

In [18]:
df.duplicated().sum()

np.int64(0)

In [20]:
df['CouponCode']=df['CouponCode'].fillna('No Coupon')

In [25]:
for col in df.columns:
    print(f'==={col}===')
    print(df[col].value_counts())
    print('\n')

===OrderID===
OrderID
ORD200000    1
ORD200806    1
ORD200804    1
ORD200803    1
ORD200802    1
            ..
ORD200399    1
ORD200398    1
ORD200397    1
ORD200396    1
ORD201199    1
Name: count, Length: 1200, dtype: int64


===Date===
Date
2023-08-20    8
2024-04-07    7
2024-11-24    6
2024-12-19    6
2025-03-15    6
             ..
2023-08-07    1
2023-03-05    1
2025-02-26    1
2024-08-19    1
2024-08-22    1
Name: count, Length: 671, dtype: int64


===CustomerID===
CustomerID
C38840    2
C14847    2
C21191    2
C94569    2
C46651    2
         ..
C99217    1
C30010    1
C70148    1
C39906    1
C57502    1
Name: count, Length: 1189, dtype: int64


===Product===
Product
Printer    181
Tablet     179
Chair      178
Laptop     173
Desk       170
Monitor    163
Phone      156
Name: count, dtype: int64


===Quantity===
Quantity
1    255
4    251
2    240
3    237
5    217
Name: count, dtype: int64


===UnitPrice===
UnitPrice
183.67    2
127.18    2
629.34    2
228.91    2
133.39    2
         ..
423.93    1
53.93     1
427.06    1
287.13    1
560.58    1
Name: count, Length: 1193, dtype: int64


===ShippingAddress===
ShippingAddress
533 Main St    8
895 Main St    6
146 Main St    5
562 Main St    5
636 Main St    5
              ..
520 Main St    1
459 Main St    1
539 Main St    1
556 Main St    1
201 Main St    1
Name: count, Length: 655, dtype: int64


===PaymentMethod===
PaymentMethod
Online         258
Cash           246
Credit Card    234
Debit Card     232
Gift Card      230
Name: count, dtype: int64


===OrderStatus===
OrderStatus
Cancelled    250
Returned     247
Pending      237
Shipped      235
Delivered    231
Name: count, dtype: int64


===TrackingNumber===
TrackingNumber
TRK37947903    1
TRK13775054    1
TRK11868618    1
TRK45098068    1
TRK34440714    1
              ..
TRK32012588    1
TRK98925264    1
TRK86674704    1
TRK82004594    1
TRK51116746    1
Name: count, Length: 1200, dtype: int64


===ItemsInCart===
ItemsInCart
5     191
6     190
4     163
7     151
8     129
3     123
9      79
2      78
1      50
10     46
Name: count, dtype: int64


===CouponCode===
CouponCode
FREESHIP     313
No Coupon    309
WINTER15     292
SAVE10       286
Name: count, dtype: int64


===ReferralSource===
ReferralSource
Instagram    259
Email        250
Google       241
Facebook     228
Referral     222
Name: count, dtype: int64


===TotalPrice===
TotalPrice
211.14     2
635.90     2
367.34     2
410.52     2
2517.36    2
          ..
538.68     1
640.88     1
2119.65    1
269.65     1
2242.32    1
Name: count, Length: 1195, dtype: int64